### ISSUE TITLE
underscore handling in figure directories

### ISSUE THREAD

**Issue by ashander** [PoisotLab/PLMT#10]
Referencing  a figure in a subdirectory with an underscore, e.g. `my_fig/figure1.png` as in [this diff](https://github.com/ashander/PLMT/commit/38189ba5d825fb97573c671fbc127eb332e3d2ac)
causes an error because the underscore is escaped at some point before translation into latex:

``` sh
pandoc ms.md_m.md -o ms.pdf --template plmt.tex --variable=draft  --filter pandoc-citeproc
! Package pdftex.def Error: File `my\T1\textunderscorefig/figure1.png' not foun
d.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.255 ...cs[width=\textwidth]{my\_fig/figure1.png}

pandoc: Error producing PDF from TeX source
make: *** [ms.pdf] Error 43
```

**Comment by tpoisot** [comment]
It's going to be a while before I can look at this, but I'll definitely do. Weird.

**Comment by ashander** [comment]
Thanks for the heads up on timing. I agree it's weird but not a big deal to
work around.

If it becomes a real problem I'll give it a shot myself and PR
