### ISSUE TITLE
Referencing/bibliography

### ISSUE THREAD

**Issue by ashander** [PoisotLab/PLMT#4]
I see you have `--filter pandoc-citeproc` in the Makefile. But the example ms and README provide no examples of integrating external references.

PS Thanks for this. I've been meaning to move drafting to markdown, and it looks like a great setup.

(Edited)

**Comment by tpoisot** [comment]
You just need to uncomment the bibliography (and csl) lines in the yaml header and it will work -- using the standard @key syntax. 

Glad you find it useful!

**Comment by ashander** [comment]
Thanks! I see 276e3bc42 adds an example
