### ISSUE TITLE
Grep options conflict

### ISSUE THREAD

**Issue by ashander** [PoisotLab/PLMT#6]
I get a warning that `z` and `P` conflict. It works for me with `Z` instead. 

https://github.com/ashander/PLMT/commit/daca636527b8373b03f4c22d118fcd2364a46d87

**Comment by tpoisot** [comment]
Can you givr me your os, and grep version?

**Comment by ashander** [comment]
Sorry. I should have added, I am not meeting system reqs re pandoc. And my OS is very old, so don't expect a fix, this is more an FYI. 

That said, version info is:

```
OS X 10.6.8
pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013)
pandoc 1.12.4.2
grep (GNU grep) 2.5.1
```

More details: https://github.com/ashander/PLMT/pull/1

**Comment by tpoisot** [comment]
OK, so as in #7, this is probably because of legacy systems. I'll try to reproduce (I have an OS X 10.5 machine somewhere) and see how much I can fix. Gonna close for now.

**Comment by ashander** [comment]
Cool. Like I mentioned, filing the issue wasn't intended to say it should be fixed. 

FWIW, the fix to `Z` works for me, but unsure if that breaks other behaviour for you.

PS thanks again, with my fixes  https://github.com/ashander/PLMT/pull/1 its working pretty smoothly for me so far

**Comment by tpoisot** [comment]
Could you perhaps edit the `README` to mention the fixes to do to make it run on not up-to-date systems? That would probably be useful!

t

**Comment by ashander** [comment]
Sure no problem. 

Good solution to make workarounds more visible if others have issues

- Jaime
