### ISSUE TITLE
Figures do not display in preprint mode

### ISSUE THREAD

**Issue by ashander** [PoisotLab/PLMT#7]
For me, removing the twocolumn option to documentclass [works for me](https://github.com/ashander/PLMT/commit/d2fe3ba61a3a6a93149fa81b002dfa8d2e1b24d8)

![screen shot 2015-07-13 at 11 10 01 am](https://cloud.githubusercontent.com/assets/510776/8656976/bd345928-294f-11e5-9410-fbefda10358b.png)

**Comment by tpoisot** [comment]
I can't reproduce. Which latex distribution are you using? OS?

**Comment by ashander** [comment]
Sorry. I should have added, I am not meeting system reqs re pandoc. And my OS is very old, so don't expect a fix, this is more an FYI if others have similar issues with antiquated setups. 

That said, version info is:

```
OS X 10.6.8
pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013)
pandoc 1.12.4.2
grep (GNU grep) 2.5.1
```

More details: https://github.com/ashander/PLMT/pull/1
